# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 06:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('beacon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rssis', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
